export const doctors = [
  {
    id: 1,
    name: "Dr. Nigar Muradova",
    title: "Qulaq Burun Boğaz cərrahi, Otonevroloq",
    image: "/images/doctor1.png",
    experience: "5 il",
    patientCount: 0,
    reviewCount: 0,
    position: "Qulaq Burun Boğaz Cərrahi, Otonevroloq",
    center: "Başgicəllənmə Mərkəzi",
    education: [
      "2010-cu ildə Azərbaycan Tibb Universiteti fərqlənmə diplomu ilə bitirmişdir.",
      "2010-2011 ci illərdə Qulaq Burun Boğaz ixtisası üzrə internatura keçmişdir.",
      "2015 ci ildə Türkiyə, İzmir Ege Universiteti Qulaq Burun Boğaz anabilim dalında ixtisaslaşmışdır.",
      "2018-2019 cu illərdə Türkiyə Ankara, Başkent Universiteti Nörotoloji kliniyində əğitim almışdır.",
    ],
    services: [
      "Pediatrik əməliyyatlar- Tonzillektomiya,",
      "Adenoidektomiya, Qulaq pərdəsinə tüp taxılması",
      "Septoplastika (burun çəpərinin düzəldilməsi)",
      "Burun balıqqulaqlarina radiofrekans tətbiqi (konxalara)",
      "Burun sinüsi əməliyyatı (açıq və qapalı reduksiya)",
      "Polipotomiya; FESC (funksional endoskopik sinus cərrahiyyəsi)",
      "Rinoplastika",
      "Qulaq şeyvanının plastikası",
      "Timpanoplastika",
      "Miringoplastika",
      "Mastoidektomiya",
      "Stapedektomiya",
      "Qulaq törəmələri",
      "Xoanal atreziya",
    ],
    articles: [],
    reviews: [],
  },
  {
    id: 2,
    name: "Dr. Nuray Şükürova",
    title: "Qulaq Burun Boğaz cərrahı",
   image: "/images/doctor2.png",
    experience: "5 il",
    patientCount: 0,
    reviewCount: 0,
    position: "Qulaq Burun Boğaz Cərrahi, Otonevroloq",
    center: "Başgicəllənmə Mərkəzi",
    education: [
      "2010-cu ildə Azərbaycan Tibb Universiteti fərqlənmə diplomu ilə bitirmişdir.",
      "2010-2011 ci illərdə Qulaq Burun Boğaz ixtisası üzrə internatura keçmişdir.",
      "2015 ci ildə Türkiyə, İzmir Ege Universiteti Qulaq Burun Boğaz anabilim dalında ixtisaslaşmışdır.",
      "2018-2019 cu illərdə Türkiyə Ankara, Başkent Universiteti Nörotoloji kliniyində əğitim almışdır.",
    ],
    services: [
      "Pediatrik əməliyyatlar- Tonzillektomiya,",
      "Adenoidektomiya, Qulaq pərdəsinə tüp taxılması",
      "Septoplastika (burun çəpərinin düzəldilməsi)",
      "Burun balıqqulaqlarina radiofrekans tətbiqi (konxalara)",
      "Burun sinüsi əməliyyatı (açıq və qapalı reduksiya)",
      "Polipotomiya; FESC (funksional endoskopik sinus cərrahiyyəsi)",
      "Rinoplastika",
      "Qulaq şeyvanının plastikası",
      "Timpanoplastika",
      "Miringoplastika",
      "Mastoidektomiya",
      "Stapedektomiya",
      "Qulaq törəmələri",
      "Xoanal atreziya",
    ],
    articles: [],
    reviews: [],
  },
  {
    id: 3,
    name: "Dr. Kamilə Allahverdiyeva",
    title: "Qulaq Burun Boğaz həkimi",
    image: "/images/doctor3.png",
    experience: "5 il",
    patientCount: 0,
    reviewCount: 0,
    position: "Qulaq Burun Boğaz Cərrahi, Otonevroloq",
    center: "Başgicəllənmə Mərkəzi",
    education: [
      "2010-cu ildə Azərbaycan Tibb Universiteti fərqlənmə diplomu ilə bitirmişdir.",
      "2010-2011 ci illərdə Qulaq Burun Boğaz ixtisası üzrə internatura keçmişdir.",
      "2015 ci ildə Türkiyə, İzmir Ege Universiteti Qulaq Burun Boğaz anabilim dalında ixtisaslaşmışdır.",
      "2018-2019 cu illərdə Türkiyə Ankara, Başkent Universiteti Nörotoloji kliniyində əğitim almışdır.",
    ],
    services: [
      "Pediatrik əməliyyatlar- Tonzillektomiya,",
      "Adenoidektomiya, Qulaq pərdəsinə tüp taxılması",
      "Septoplastika (burun çəpərinin düzəldilməsi)",
      "Burun balıqqulaqlarina radiofrekans tətbiqi (konxalara)",
      "Burun sinüsi əməliyyatı (açıq və qapalı reduksiya)",
      "Polipotomiya; FESC (funksional endoskopik sinus cərrahiyyəsi)",
      "Rinoplastika",
      "Qulaq şeyvanının plastikası",
      "Timpanoplastika",
      "Miringoplastika",
      "Mastoidektomiya",
      "Stapedektomiya",
      "Qulaq törəmələri",
      "Xoanal atreziya",
    ],
    articles: [],
    reviews: [],
  },
  {
    id: 4,
    name: "Dr. Mahtaban Qədiməli",
    title: "Qulaq Burun Boğaz cərrahı",
    image: "/images/doctor4.png",
    experience: "5 il",
    patientCount: 0,
    reviewCount: 0,
    position: "Qulaq Burun Boğaz Cərrahi, Otonevroloq",
    center: "Başgicəllənmə Mərkəzi",
    education: [
      "2010-cu ildə Azərbaycan Tibb Universiteti fərqlənmə diplomu ilə bitirmişdir.",
      "2010-2011 ci illərdə Qulaq Burun Boğaz ixtisası üzrə internatura keçmişdir.",
      "2015 ci ildə Türkiyə, İzmir Ege Universiteti Qulaq Burun Boğaz anabilim dalında ixtisaslaşmışdır.",
      "2018-2019 cu illərdə Türkiyə Ankara, Başkent Universiteti Nörotoloji kliniyində əğitim almışdır.",
    ],
    services: [
      "Pediatrik əməliyyatlar- Tonzillektomiya,",
      "Adenoidektomiya, Qulaq pərdəsinə tüp taxılması",
      "Septoplastika (burun çəpərinin düzəldilməsi)",
      "Burun balıqqulaqlarina radiofrekans tətbiqi (konxalara)",
      "Burun sinüsi əməliyyatı (açıq və qapalı reduksiya)",
      "Polipotomiya; FESC (funksional endoskopik sinus cərrahiyyəsi)",
      "Rinoplastika",
      "Qulaq şeyvanının plastikası",
      "Timpanoplastika",
      "Miringoplastika",
      "Mastoidektomiya",
      "Stapedektomiya",
      "Qulaq törəmələri",
      "Xoanal atreziya",
    ],
    articles: [],
    reviews: [],
  },
];
